[package]
name = "goup"
description = "Like rustup or nvm but for Go. 🚀"
version = "1.0.0"
edition = "2021"
authors = ["Ringo Hoffmann <contact@zekro.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.5", features = ["derive"] }
console = "0.15.5"
directories = "5.0.1"
flate2 = "1.0.26"
nom = "7.1.3"
reqwest = { version = "0.11.17", default-features = false, features = ["blocking", "rustls-tls"] }
tar = "0.4.38"
